#!/usr/bin/env python  

import actionlib
import rospy
from std_msgs.msg import Int8, Float32
from wpi_jaco_msgs.msg import CartesianCommand
from geometry_msgs.msg import Quaternion, Twist, Vector3

def handle_gripper(msg):
    global val
    if msg.data == 2: #open
        val = [0.0,0.0]
    elif msg.data == 3: #close
        val = [5250.0,5250.0]
        
    newGrip = CartesianCommand()
    newGrip.position = True
    newGrip.armCommand = False
    newGrip.fingerCommand = True
    newGrip.repeat = False
    newGrip.fingers = val
    pub.publish(newGrip)
        
if __name__ == '__main__':
    val = [0.0,0.0]
    topicName = 'HandState'
    rospy.init_node('handStateCtrl', anonymous=True)
    pub = rospy.Publisher('/mico_arm/cartesian_cmd', CartesianCommand, queue_size=5)
    rospy.Subscriber(topicName, Int8, handle_gripper, queue_size=10)
    rospy.spin()
