#!/usr/bin/env python  

import actionlib
import rospy
from std_msgs.msg import Int8, Float32
from wpi_jaco_msgs.msg import CartesianCommand
from geometry_msgs.msg import Quaternion, Twist, Vector3

def handle_gripper(msg):
    global gripper
    if msg.data == 2: #open
        val = [Float32(0.0),Float32(0.0)]
    elif msg.data == 3: #close
        val = [Float32(5250.0),Float32(5250.0)]
        
    newGrip = CartesianCommand()
    newGrip.position = True
    newPose.armCommand = False
    newPose.fingerCommand = True
    newPose.repeat = True
    newPose.fingers = val
    pub.publish(newPose)
        
if __name__ == '__main__':
    topicName = 'HandState'
    rospy.init_node('handStateCtrl', anonymous=True)
    pub = rospy.Publisher('/mico_arm/cartesian_cmd', CartesianCommand, queue_size=5)
    rospy.Subscriber(topicName, Int8, handle_gripper, queue_size=10)
    rospy.spin()
