#!/usr/bin/env python

import SocketServer
import rospy
import thread
from geometry_msgs.msg import Pose
from std_msgs.msg import Bool

class HandDataListener(SocketServer.BaseRequestHandler):
    """
    The RequestHandler class for our server. Currently only echos received data. This need to be moved into a ROS node.
    """
    def handle(self):
        """
        Handle the data stream connection.
        :return: none
        """
        self.data = self.request[0].strip()
        if self.data != "":
            rospy.loginfo("{} wrote: ".format(self.client_address[0]) + self.data)

            # split data
            splitData = self.data.split("|")
            handDisp = splitData[0].split(",")
            handRef = splitData[1].split(",")
            refChange = splitData[2]

            # publish new hand pose
            newPose = Pose()
            newPose.position.x = float(handDisp[0])
            newPose.position.y = float(handDisp[1])
            newPose.position.z = float(handDisp[2])
            newPose.orientation.x = float(handDisp[3])
            newPose.orientation.y = float(handDisp[4])
            newPose.orientation.z = float(handDisp[5])
            newPose.orientation.w = float(handDisp[6])
            hand_pose_pub.publish(newPose)
            
            # publish new ref pose
            newRefPose = Pose()
            newRefPose.position.x = 0.0
            newRefPose.position.y = 0.0
            newRefPose.position.z = 0.0
            newRefPose.orientation.x = float(handRef[0])
            newRefPose.orientation.y = float(handRef[1])
            newRefPose.orientation.z = float(handRef[2])
            newRefPose.orientation.w = float(handRef[3])
            ref_pose_pub.publish(newRefPose)
            
            # change ref frame?
            update = False
            if(refChange == "True"):
                update = True
            ref_change_pub.publish(Bool(update))
                
                

if __name__ == '__main__':
    HOST, PORT = "192.168.1.102", 5050

    # Create the server, binding to localhost on port 5050
    rospy.loginfo("Starting SocketServer...")
    server = SocketServer.UDPServer((HOST, PORT), HandDataListener)

    # function to stop listening (requires new thread)
    def ROSShutdown():
        rospy.loginfo("Attempting shutdown of SocketServer...")
        #hand_pose_pub.unregister()
        #ref_pose_pub.unregister()
        def StopSocketListener(_s):
            _s.shutdown()
            
        thread.start_new_thread(StopSocketListener, (server,))
        rospy.loginfo("...Done!")

    # start ROS node and publishers
    rospy.init_node('HandDataListener', anonymous=True)
    rospy.on_shutdown(ROSShutdown)
    hand_pose_pub = rospy.Publisher('HandPose', Pose, queue_size=50)
    ref_pose_pub = rospy.Publisher('RefPose', Pose, queue_size=50)
    ref_change_pub = rospy.Publisher('RefChange', Bool, queue_size=50)

    # Activate the server; this will keep running until you
    # interrupt the program with Ctrl-C
    rospy.loginfo("SocketServer listening for connections...")
    server.serve_forever()
