#!/usr/bin/env python  

import roslib
import rospy
import tf
from geometry_msgs.msg import Pose

def handle_pose(msg, (fName,pName)):
    br = tf.TransformBroadcaster()
    br.sendTransform((-msg.position.x, msg.position.y, msg.position.z),
        (msg.orientation.x, msg.orientation.y, msg.orientation.z, msg.orientation.w),
        rospy.Time.now(),
        fName,
        pName)
        
if __name__ == '__main__':
    topicName = 'HandPose'
    frameName = "hand_disp_frame"
    parentName = "kinect_frame"
    rospy.init_node('handBroadcaster', anonymous=True)
    rospy.Subscriber(topicName,Pose,handle_pose,(frameName,parentName), queue_size=10)
    rospy.spin()
