#!/usr/bin/env python  

import roslib
import rospy
import tf
from geometry_msgs.msg import Pose

def handle_pose(msg, (fName, pName)):
    br = tf.TransformBroadcaster()
    br.sendTransform((0.0,0.0,0.0),
        #(msg.orientation.x, msg.orientation.y, msg.orientation.z, msg.orientation.w),
        (0.0, 0.0, 0.0, 1.0),
        rospy.Time.now(),
        fName,
        pName)

if __name__ == '__main__':
    topicName = 'RefPose'
    frameName = "hand_ref_frame"
    parentName = "kinect_frame"
    rospy.init_node('redBroadcaster', anonymous=True)
    rospy.Subscriber(topicName,Pose,handle_pose,(frameName,parentName), queue_size=10)
    rospy.spin()
